/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

// Rough delay function for initialization
void delay_ms(volatile uint32_t ms) {
    ms *= 16000; // Adjust this multiplier if your delay is too fast/slow
    while(ms--) { __NOP(); }
}

int main(void)
{
    /* Loop forever */
	for(;;);
}
